select current_region();

select current_region(),
current_account()

CREATE OR REPLACE STORAGE INTEGRATION s3_weather_integration
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::119408973487:role/snowflake-s3-role-1'
STORAGE_ALLOWED_LOCATIONS = ('s3://mayukh-weather-data-2026-119408973487-ap-southeast-1-an/');

DESC INTEGRATION s3_weather_integration;

show databases;

use database "USER$MAYUKH2003";



create database WEATHER_DB;

USE DATABASE WEATHER_DB;
CREATE SCHEMA IF NOT EXISTS PUBLIC;

use schema public;

CREATE OR REPLACE STAGE weather_stage
STORAGE_INTEGRATION = s3_weather_integration
URL = 's3://mayukh-weather-data-2026-119408973487-ap-southeast-1-an/';

LIST @weather_stage;

desc stage weather_stage;


CREATE OR REPLACE TABLE weather_data (
    city STRING,
    country STRING,
    temperature FLOAT,
    humidity INTEGER,
    pressure INTEGER,
    weather STRING,
    wind_speed FLOAT,
    observation_time TIMESTAMP
);

CREATE OR REPLACE FILE FORMAT weather_json_format
TYPE = JSON;

show databases;

show schemas;

show tables;

DESCRIBE TABLE WEATHER_DB.PUBLIC.WEATHER_DATA;
show storage integrations;

DESC INTEGRATION S3_WEATHER_INTEGRATION;

USE DATABASE WEATHER_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE FILE FORMAT WEATHER_JSON_FORMAT
TYPE = JSON;

ALTER STORAGE INTEGRATION S3_WEATHER_INTEGRATION
SET STORAGE_ALLOWED_LOCATIONS = (
    's3://mayukh-weather-data-2026-119408973487-ap-southeast-1-an/'
);

CREATE OR REPLACE STAGE WEATHER_STAGE
URL = 's3://mayukh-weather-data-2026-119408973487-ap-southeast-1-an/'
STORAGE_INTEGRATION = S3_WEATHER_INTEGRATION
FILE_FORMAT = WEATHER_JSON_FORMAT;

LIST @WEATHER_STAGE;

COPY INTO WEATHER_DATA
FROM @WEATHER_STAGE
FILE_FORMAT = (FORMAT_NAME = WEATHER_JSON_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

SELECT * FROM WEATHER_DATA;

SELECT * FROM WEATHER_DATA ORDER BY OBSERVATION_TIME DESC;

SELECT $1 FROM @WEATHER_STAGE LIMIT 1;
SELECT COUNT(*) AS TOTAL_ROWS FROM WEATHER_DATA;

TRUNCATE TABLE WEATHER_DATA;

INSERT INTO WEATHER_DATA
(
    CITY,
    COUNTRY,
    TEMPERATURE,
    HUMIDITY,
    PRESSURE,
    WEATHER,
    WIND_SPEED,
    OBSERVATION_TIME
)
SELECT
    $1:city::VARCHAR,
    NULL,
    $1:temperature::FLOAT,
    $1:humidity::NUMBER(38,0),
    NULL,
    $1:weather::VARCHAR,
    NULL,
    $1:timestamp::TIMESTAMP_NTZ
FROM @WEATHER_STAGE
(FILE_FORMAT => WEATHER_JSON_FORMAT);

SELECT COUNT(*) AS TOTAL_ROWS FROM WEATHER_DATA;
SELECT * FROM WEATHER_DATA ORDER BY OBSERVATION_TIME DESC;
SELECT COUNT(*) AS total_records FROM WEATHER_DATA;

SELECT
    MIN(TEMPERATURE) AS min_temperature,
    MAX(TEMPERATURE) AS max_temperature,
    AVG(TEMPERATURE) AS avg_temperature,
    AVG(HUMIDITY) AS avg_humidity
FROM WEATHER_DATA;

SELECT
    WEATHER,
    COUNT(*) AS OCCURRENCES
FROM WEATHER_DATA
GROUP BY WEATHER
ORDER BY OCCURRENCES DESC;

SELECT
    ROUND(AVG(TEMPERATURE), 2) AS AVG_TEMPERATURE,
    ROUND(AVG(HUMIDITY), 2) AS AVG_HUMIDITY,
    ROUND(MIN(TEMPERATURE), 2) AS MIN_TEMPERATURE,
    ROUND(MAX(TEMPERATURE), 2) AS MAX_TEMPERATURE,
    ROUND(MIN(HUMIDITY), 2) AS MIN_HUMIDITY,
    ROUND(MAX(HUMIDITY), 2) AS MAX_HUMIDITY
FROM WEATHER_DATA;

SELECT
    OBSERVATION_TIME,
    TEMPERATURE,
    HUMIDITY,
    WEATHER
FROM WEATHER_DATA
ORDER BY OBSERVATION_TIME;

select current_database(),current_schema();
show tables;