CREATE DATABASE WEATHER_DB;
USE DATABASE WEATHER_DB;
USE SCHEMA PUBLIC;
SELECT CURRENT_DATABASE(),CURRENT_SCHEMA();

CREATE TABLE WEATHER_DATA (
    CITY STRING,
    COUNTRY STRING,
    TEMPERATURE FLOAT,
    HUMIDITY INTEGER,
    PRESSURE STRING,
    WEATHER STRING,
    WIND_SPEED FLOAT,
    OBSERVATION_TIME TIMESTAMP
    
);
SHOW TABLES;

CREATE OR REPLACE FILE FORMAT 
WEATHER_JSON_FORMAT
TYPE = JSON;

CREATE OR REPLACE STORAGE INTEGRATION S3_WEATHER_INTEGRATION
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN =
'arn:aws:iam::119408973487:role/snowflake-s3-role-1'
STORAGE_ALLOWED_LOCATIONS = (
    's3://mayukh-weather-data-2026-119408973487-ap-southeast-1-an/'
);

DESC INTEGRATION 
S3_WEATHER_INTEGRATION;


USE DATABASE WEATHER_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE STAGE WEATHER_STAGE
URL = 's3://mayukh-weather-data-2026-119408973487-ap-southeast-1-an/'
STORAGE_INTEGRATION = S3_WEATHER_INTEGRATION
FILE_FORMAT = WEATHER_JSON_FORMAT;

list @weather_stage;

COPY INTO WEATHER_DATA
FROM @WEATHER_STAGE
FILE_FORMAT = (FORMAT_NAME = WEATHER_JSON_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) AS TOTAL_ROWS
FROM WEATHER_DATA;
SELECT *
FROM WEATHER_DATA
ORDER BY OBSERVATION_TIME DESC;

SELECT CURRENT_REGION(),
CURRENT_ACCOUNT();

USE DATABASE WEATHER_DB;
USE SCHEMA PUBLIC;

SHOW STORAGE INTEGRATIONS;

DESC INTEGRATION
S3_WEATHER_INTEGRATION;

CREATE OR REPLACE FILE FORMAT WEATHER_JSON_FORMAT
TYPE = JSON;

SHOW FILE FORMATS;

CREATE OR REPLACE STAGE WEATHER_STAGE
URL = 's3://mayukh-weather-data-2026-119408973487-ap-southeast-1-an/'
STORAGE_INTEGRATION = S3_WEATHER_INTEGRATION
FILE_FORMAT = WEATHER_JSON_FORMAT;

LIST @WEATHER_STAGE;

CREATE OR REPLACE TABLE WEATHER_DATA (
    CITY STRING,
    COUNTRY STRING,
    TEMPERATURE FLOAT,
    HUMIDITY INTEGER,
    PRESSURE INTEGER,
    WEATHER STRING,
    WIND_SPEED FLOAT,
    OBSERVATION_TIME TIMESTAMP
);

DESC TABLE WEATHER_DATA;

COPY INTO WEATHER_DATA
FROM @WEATHER_STAGE
FILE_FORMAT = (FORMAT_NAME = WEATHER_JSON_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

SELECT *
FROM WEATHER_DATA
ORDER BY OBSERVATION_TIME DESC
LIMIT 10;

SELECT
    CITY,
    COUNTRY,
    TEMPERATURE,
    HUMIDITY,
    PRESSURE,
    WEATHER,
    WIND_SPEED,
    OBSERVATION_TIME
FROM WEATHER_DATA
WHERE CITY = 'Kochi'
ORDER BY OBSERVATION_TIME DESC
LIMIT 10;

SELECT
    $1,
    METADATA$FILENAME
FROM @WEATHER_STAGE
    (FILE_FORMAT => WEATHER_JSON_FORMAT)
WHERE METADATA$FILENAME ILIKE '%Kochi_2026-10-02%';

COPY INTO WEATHER_DATA
FROM @WEATHER_STAGE
FILE_FORMAT = (FORMAT_NAME = WEATHER_JSON_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE'
FORCE = TRUE;

SELECT
    CITY,
    COUNTRY,
    TEMPERATURE,
    HUMIDITY,
    PRESSURE,
    WEATHER,
    WIND_SPEED,
    OBSERVATION_TIME
FROM WEATHER_DATA
WHERE CITY = 'Kochi'
ORDER BY OBSERVATION_TIME DESC
LIMIT 10;

SELECT
    $1:city::STRING AS CITY,
    $1:country::STRING AS COUNTRY,
    $1:temperature::FLOAT AS TEMPERATURE,
    $1:humidity::INTEGER AS HUMIDITY,
    $1:pressure::INTEGER AS PRESSURE,
    $1:weather::STRING AS WEATHER,
    $1:wind_speed::FLOAT AS WIND_SPEED,
    $1:observation_time::TIMESTAMP AS OBSERVATION_TIME,
    METADATA$FILENAME AS FILE_NAME
FROM @WEATHER_STAGE
    (FILE_FORMAT => WEATHER_JSON_FORMAT)
WHERE METADATA$FILENAME ILIKE '%Kochi_2026-10-02%'
LIMIT 10;

INSERT INTO WEATHER_DATA
(
    CITY,
    COUNTRY,
    TEMPERATURE,
    HUMIDITY,
    PRESSURE,
    WEATHER,
    WIND_SPEED,
    OBSERVATION_TIME
)
SELECT
    $1:city::STRING,
    $1:country::STRING,
    $1:temperature::FLOAT,
    $1:humidity::INTEGER,
    $1:pressure::INTEGER,
    $1:weather::STRING,
    $1:wind_speed::FLOAT,
    $1:observation_time::TIMESTAMP
FROM @WEATHER_STAGE
    (FILE_FORMAT => WEATHER_JSON_FORMAT)
WHERE METADATA$FILENAME ILIKE '%Kochi_2026-10-02%';

SELECT
    CITY,
    COUNTRY,
    TEMPERATURE,
    HUMIDITY,
    PRESSURE,
    WEATHER,
    WIND_SPEED,
    OBSERVATION_TIME
FROM WEATHER_DATA
WHERE CITY = 'Kochi'
  AND OBSERVATION_TIME IS NOT NULL
ORDER BY OBSERVATION_TIME DESC
LIMIT 10;

CREATE OR REPLACE PIPE WEATHER_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO WEATHER_DATA
(
    CITY,
    COUNTRY,
    TEMPERATURE,
    HUMIDITY,
    PRESSURE,
    WEATHER,
    WIND_SPEED,
    OBSERVATION_TIME
)
FROM
(
    SELECT
        $1:city::STRING,
        $1:country::STRING,
        $1:temperature::FLOAT,
        $1:humidity::INTEGER,
        $1:pressure::INTEGER,
        $1:weather::STRING,
        $1:wind_speed::FLOAT,
        $1:observation_time::TIMESTAMP
    FROM @WEATHER_STAGE
)
FILE_FORMAT = (FORMAT_NAME = WEATHER_JSON_FORMAT)
ON_ERROR = 'CONTINUE';

SHOW PIPES;
SELECT SYSTEM$PIPE_STATUS('WEATHER_PIPE');

SELECT
    CITY,
    COUNTRY,
    TEMPERATURE,
    HUMIDITY,
    PRESSURE,
    WEATHER,
    WIND_SPEED,
    OBSERVATION_TIME
FROM WEATHER_DATA
WHERE CITY = 'Kochi'
  AND OBSERVATION_TIME IS NOT NULL
ORDER BY OBSERVATION_TIME DESC
LIMIT 10;

SHOW PIPES;

